# Generated by Django 5.0.7 on 2024-09-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car_model",
            name="price",
            field=models.IntegerField(),
        ),
    ]
