# Generated by Django 5.0.7 on 2024-09-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
        ("cars", "0002_alter_car_model_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car_model",
            name="brand",
        ),
        migrations.AddField(
            model_name="car_model",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="brands.brand_model",
            ),
        ),
    ]
