# Generated by Django 5.0.7 on 2024-09-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_remove_car_model_brand_car_model_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_model",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="posts/media/uploads/"
            ),
        ),
    ]
