# Generated by Django 5.0.7 on 2024-09-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_alter_car_model_image_car_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_model",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
