# Generated by Django 5.0.7 on 2024-09-18 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0001_initial"),
        ("posts", "0002_alter_posts_model_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="author_model",
        ),
    ]
