# Generated by Django 5.0.7 on 2024-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student_model",
            fields=[
                ("name", models.CharField(max_length=30)),
                ("roll", models.IntegerField(primary_key=True, serialize=False)),
                ("fathers_name", models.CharField(max_length=30)),
                ("address", models.TextField()),
            ],
        ),
    ]
