# Generated by Django 5.0.7 on 2024-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_address",
            name="postal_code",
            field=models.IntegerField(),
        ),
    ]
