# Generated by Django 5.0.7 on 2024-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catagories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagories_model",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
