# Generated by Django 5.0.7 on 2024-09-28 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rename_books_books_model_rename_borrow_borrow_model_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrow_model",
            name="borrow_quantity",
        ),
    ]
