# Generated by Django 5.0.7 on 2024-09-27 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
        ("catagories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="books",
            new_name="books_model",
        ),
        migrations.RenameModel(
            old_name="borrow",
            new_name="borrow_model",
        ),
        migrations.RenameModel(
            old_name="comment",
            new_name="comment_model",
        ),
    ]
