# Generated by Django 5.0.7 on 2024-09-10 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catagory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catagory_model",
            name="task",
        ),
    ]
