# Generated by Django 5.0.7 on 2024-08-20 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profiles_model_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profiles_model",
            old_name="title",
            new_name="name",
        ),
    ]
