# Generated by Django 5.0.7 on 2024-08-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("author", "0001_initial"),
        ("catagories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="posts_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="author.author_model",
                    ),
                ),
                ("catagory", models.ManyToManyField(to="catagories.catagories_model")),
            ],
        ),
    ]
