# Generated by Django 5.0.7 on 2024-09-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="task_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                ("Description", models.TextField()),
                ("Assign_date", models.DateField()),
                ("is_completed", models.BooleanField()),
            ],
        ),
    ]
