# Generated by Django 5.0.7 on 2024-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catagory", "0002_remove_catagory_model_task"),
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task_model",
            name="Catagory",
            field=models.ManyToManyField(to="catagory.catagory_model"),
        ),
        migrations.AlterField(
            model_name="task_model",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
